### ISSUE TITLE
NodeCG won't mount this bundle.

### ISSUE THREAD

**Issue by ghost** [rfox90/nodecg-beam#6]
Was trying to install this bundle and got this error while trying to start it:
`error: [nodecg/lib/server/extensions] Failed to mount nodecg-beam extension: TypeError: this.connect is not a function
    at new Client (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\wsabi-client-bacon\lib\Client.js:30:8)
    at new Live (C:\Users\\Desktop\testing\bundles\nodecg-beam\lib\Live.js:17:15)
    at createLive (C:\Users\\Desktop\testing\bundles\nodecg-beam\extension.js:58:10)
    at module.exports (C:\Users\\Desktop\testing\bundles\nodecg-beam\extension.js:74:2)
    at _loadExtension (C:\Users\\Desktop\testing\lib\server\extensions.js:98:41)
    at EventEmitter.<anonymous> (C:\Users\\Desktop\testing\lib\server\extensions.js:35:21)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at C:\Users\\Desktop\testing\node_modules\@nodecg\bundle-manager\index.js:140:21
    at _fulfilled (C:\Users\\Desktop\testing\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\\Desktop\testing\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\\Desktop\testing\node_modules\q\q.js:796:13)
    at C:\Users\\Desktop\testing\node_modules\q\q.js:604:44
    at runSingle (C:\Users\\Desktop\testing\node_modules\q\q.js:137:13)
    at flush (C:\Users\\Desktop\testing\node_modules\q\q.js:125:13)
    at doNTCallback0 (node.js:419:9)`

**Comment by ProbablePrime** [comment]
Are you running on nodecg 0.7 or 0.6? I can't immediately tell from your stack trace. 

It's puzzling as that method is defined in wsabi-client-bacon, which i also wrote. 

It might have something to do with how nodecg is mounting the bundle. I'll try a clean install for you.

**Comment by ghost** [comment]
I'm running nodecg 0.7.1 with node 4.2.2.

**Comment by ProbablePrime** [comment]
I've got a clean nodecg install. I'll get back to you with what I find.

Thanks for the report!

**Comment by ProbablePrime** [comment]
I've bumped project dependencies and verified it works on a clean nodecg install could you try again.

try deleting `C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\wsabi-client-bacon\`

and clearing your npm cache and then restarting nodecg.

**Comment by ghost** [comment]
Still getting the same error.

**Comment by ProbablePrime** [comment]
Could you open `C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\wsabi-client-bacon\lib\Client.js` and dump it to pastebin.

Thanks!

**Comment by ghost** [comment]
Here it is http://pastebin.com/BiEnhMmy

**Comment by ProbablePrime** [comment]
Just wanted to let you know I have read this.

I've got everything I need to workout why you are having an issue and will get back to you when I can!

**Comment by ProbablePrime** [comment]
@ripbandit I've updated the underlying beam ws client to avoid `this` and am writing some tests for it so we can rule out it as a cause.

If you can git pull the bundle itll figure out that it needs to go grab 0.1.3 of `wsabi-client-bacon`. After that please try again.

Let me know! this one is driving me mental :). Oh and what is your underlying Node version?

**Comment by ghost** [comment]
I'm getting a slightly different error now. I'm using Node v4.2.2. 
`error: [nodecg/lib/server/extensions] Failed to mount nodecg-beam extension: TypeError: self.connect is not a function
    at new Client (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\wsabi-client-bacon\lib\Client.js:33:8)
    at new Live (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\lib\Live.js:17:15)
    at createLive (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\extension.js:57:10)
    at module.exports (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\extension.js:73:2)
    at _loadExtension (C:\Users\Rip\Desktop\testing\lib\server\extensions.js:98:41)
    at EventEmitter.<anonymous> (C:\Users\Rip\Desktop\testing\lib\server\extensions.js:35:21)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at C:\Users\Rip\Desktop\testing\node_modules\@nodecg\bundle-manager\index.js:140:21
    at _fulfilled (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:796:13)
    at C:\Users\Rip\Desktop\testing\node_modules\q\q.js:604:44
    at runSingle (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:137:13)
    at flush (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:125:13)
    at doNTCallback0 (node.js:419:9)`

**Comment by ProbablePrime** [comment]
D:.

Ok, can you be super helpful and in C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\wsabi-client-bacon\lib\Client.js

add a new line around line 33 with `console.log(self)` and then restart nodecg that will let me know what nodecg thinks the current context is at that execution point.

Something somewhere is either rebinding `this` or doing some really weird.

Do you have any other bundles in the installation.

Thanks so much for continuing to help me out with this!

**Comment by ghost** [comment]
I don't have any other bundles in this install yet. Here's the result of the console.log: 
`EventEmitter {
  liveUrl: '/api/v1/live',
  subscriptions: {},
  socket:
   EventEmitter {
     url: 'https://beam.pro',
     messageId: 0,
     waiting: {},
     reconnecting: false,
     pingInterval: 25000,
     sid: '',
     reconnectionDelay: 1000,
     domain: null,
     _events: { reopen: [Function], error: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined } }`

**Comment by ProbablePrime** [comment]
I understand the problem now. Many thanks!

**Comment by ProbablePrime** [comment]
Yup its a node version problem. I've replicated it on a machine thats running the exact same version as you. Now I can reproduce it. I'll solve it

**Comment by ProbablePrime** [comment]
@ripbandit try now do a git pull etc as before

Thanks so much. I was seriously abusing prototype chains that works with node 5 but node 4 complains. Better to do it the old way :D

**Comment by ghost** [comment]
Am now getting a different error that crashed NodeCG:.

```
error: [nodecg/lib/server/extensions] Failed to mount nodecg-beam extension: TypeError: this.log is not a function
    at new Channel (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\lib\Channel.js:10:7)
    at C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\extension.js:67:29
    at Array.forEach (native)
    at addChannels (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\extension.js:65:32)
    at module.exports (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\extension.js:74:2)
    at _loadExtension (C:\Users\Rip\Desktop\testing\lib\server\extensions.js:98:41)
    at EventEmitter.<anonymous> (C:\Users\Rip\Desktop\testing\lib\server\extensions.js:35:21)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at C:\Users\Rip\Desktop\testing\node_modules\@nodecg\bundle-manager\index.js:140:21
    at _fulfilled (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:796:13)
    at C:\Users\Rip\Desktop\testing\node_modules\q\q.js:604:44
    at runSingle (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:137:13)
    at flush (C:\Users\Rip\Desktop\testing\node_modules\q\q.js:125:13)
info: [nodecg/lib/server] NodeCG running on http://localhost:9090
UNCAUGHT EXCEPTION! NodeCG will now exit.
TypeError: self.log is not a function
    at null.<anonymous> (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\lib\Live.js:23:8)
    at emitNone (events.js:67:13)
    at emit (events.js:166:7)
    at Socket._handleSocketMessage (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\wsabi-client-bacon\lib\Socket.js:66:9)
    at WebSocket.<anonymous> (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\wsabi-client-bacon\lib\Socket.js:25:15)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\ws\lib\WebSocket.js:816:10)
    at C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\ws\lib\Receiver.js:477:18
    at C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\ws\lib\Receiver.js:361:7
    at C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\ws\lib\PerMessageDeflate.js:247:5
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:5)
    at TransformState.afterTransform (_stream_transform.js:54:12)
```

**Comment by ProbablePrime** [comment]
Allright, go for it once more updating to 3.0.3 with a git pull.

Thanks so much for testing this out in node 4 :)

**Comment by ghost** [comment]
There's progress at least, NodeCG mounts it now but it gives an error right on start.

```
info: [nodecg-beam] polling followers
[ 0 ]
Unhandled rejection TypeError: Cannot read property 'reverse' of undefined
    at C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\lib\Live.js:186:12
    at tryCatcher (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise.js:491:31)
    at Promise._settlePromise (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise.js:617:18)
    at PromiseArray._resolve (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise.js:553:26)
    at Promise._settlePromise0 (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\promise.js:676:18)
    at Async._drainQueue (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\async.js:125:16)
    at Async._drainQueues (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Rip\Desktop\testing\bundles\nodecg-beam\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by ProbablePrime** [comment]
Which channel are you sending it to look at?

**Comment by ProbablePrime** [comment]
Ahh i got it. If you have less than 100 followers its going to bork. 

I'm sorry. I'll get that fixed shortly.

Thanks so much!

**Comment by ProbablePrime** [comment]
Alright Try now, "Fingers crossed" :D!

**Comment by ghost** [comment]
IT WORKS! Thanks for the fix!

**Comment by ProbablePrime** [comment]
No problem. Thank you so much for the support in throwing log messages at me
